# Generated by Django 5.0 on 2024-07-11 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrityportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='integrityportal.office'),
            preserve_default=False,
        ),
    ]
