# Generated by Django 5.0 on 2024-07-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrityportal', '0002_case_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='integrityportal.office'),
        ),
    ]
