# Generated by Django 5.0.6 on 2024-05-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrityportal', '0002_alter_case_hearing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='decision',
            field=models.CharField(choices=[('no_decision', 'No Decision'), ('suspended', 'Suspended'), ('probation', 'Probation'), ('forgiven', 'Forgiven')], default='no_decision', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
