# Generated by Django 5.0 on 2024-07-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrityportal', '0004_suspensionletter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='suspensionletter',
            unique_together=set(),
        ),
    ]
