# Generated by Django 5.0 on 2024-07-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrityportal', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
